/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontEnd;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author HOME
 */
public class PromotionOfPawnWhite extends javax.swing.JDialog {
    String type;
    /**
     * Creates new form PromotionOfPawnWhite
     * @param parent
     * @param modal
     */
    public PromotionOfPawnWhite(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        type="";
        this.setLocation((Toolkit.getDefaultToolkit().getScreenSize().width)/2-140,20);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Queen = new javax.swing.JLabel();
        Rook = new javax.swing.JLabel();
        Bishop = new javax.swing.JLabel();
        Knight = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(290, 402));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        Queen.setBackground(new java.awt.Color(0, 153, 153));
        Queen.setIcon(to("white queen"));
        Queen.setText("Queen");
        Queen.setOpaque(true);
        Queen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QueenMouseClicked(evt);
            }
        });

        Rook.setBackground(new java.awt.Color(0, 153, 153));
        Rook.setText("Rook");
        Rook.setOpaque(true);
        Rook.setIcon(to("white rook"));
        Rook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RookMouseClicked(evt);
            }
        });

        Bishop.setIcon(to("white bishop"));
        Bishop.setBackground(new java.awt.Color(0, 153, 153));
        Bishop.setText("Bishop");
        Bishop.setOpaque(true);
        Bishop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BishopMouseClicked(evt);
            }
        });

        Knight.setBackground(new java.awt.Color(0, 153, 153));
        Knight.setText("Knight");
        Knight.setOpaque(true);
        Knight.setIcon(to("white knight"));
        Knight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KnightMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(Queen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(Rook, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(Bishop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(Knight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(19, 19, 19)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Queen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Rook, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Bishop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Knight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QueenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QueenMouseClicked
        type="Queen";
        this.dispose();
    }//GEN-LAST:event_QueenMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void RookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RookMouseClicked
        type="Rook";
        this.dispose();
    }//GEN-LAST:event_RookMouseClicked

    private void BishopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BishopMouseClicked
        type="Bishop";
        this.dispose();
    }//GEN-LAST:event_BishopMouseClicked

    private void KnightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KnightMouseClicked
        type="Knight";
        this.dispose();
    }//GEN-LAST:event_KnightMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PromotionOfPawnWhite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            PromotionOfPawnWhite dialog;dialog = new PromotionOfPawnWhite(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }
    public boolean isAnythingSelected()
    {
        switch(type)
        {
            case "":
                return false;
            default:
                return true;
        }
    }
    public String Choice()
    {
        return type;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bishop;
    private javax.swing.JLabel Knight;
    private javax.swing.JLabel Queen;
    private javax.swing.JLabel Rook;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    private ImageIcon getImageIcon(String path)
    {
        ImageIcon Myimage=new ImageIcon(getClass().getResource(path));
        Image img=Myimage.getImage();
        Image newImg=img.getScaledInstance(60,60,Image.SCALE_SMOOTH);
        ImageIcon ico=new ImageIcon(newImg);
        return ico;
    }
    public ImageIcon to(String imageName)
    {
        return getImageIcon("/Images/"+imageName+".png");
    }
    public void setTypeToNull()
    {
        type="";
    }
}
